# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14371eb95fa7e82edc8616cc5846658c2e46cf1aa87659d44a98a43e2553b67cd694ce2830d3bcaa0b825a6cac75630edbc90259f0c385542649f9d2dd317ade

test:
  secret_key_base: 3bea3534caabb7a10aff3eb608a3fca3caecd176913400cd7069f05e73eac69a96d693b80bf99d65c8a4627bf28520d41bea610d4d83699d7d7f0a16a03d1380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
